# Generated by Django 6.1 on 2026-09-01 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(help_text="Human-readable explanation, e.g. 'Recommended based on 5 similar students'", max_length=255)),
                ('confidence', models.FloatField(default=0.0, help_text='Fraction of nearest neighbors who improved after this lesson')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('recommended_lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.lesson')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='accounts.student')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.topic')),
            ],
        ),
        migrations.CreateModel(
            name='StudentTopicFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_score', models.FloatField(default=0.0)),
                ('assignment_score', models.FloatField(default=0.0)),
                ('coding_score', models.FloatField(default=0.0)),
                ('avg_attempts_before_pass', models.FloatField(default=0.0)),
                ('avg_submission_time_seconds', models.FloatField(default=0.0)),
                ('attendance_rate', models.FloatField(default=0.0)),
                ('is_weak', models.BooleanField(blank=True, null=True)),
                ('weak_probability', models.FloatField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_features', to='accounts.student')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_features', to='academics.topic')),
            ],
            options={
                'unique_together': {('student', 'topic')},
            },
        ),
    ]
