"""
Django settings for codelearn project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def _env_bool(name, default=False):
    return os.environ.get(name, str(default)).strip().lower() in ("1", "true", "yes", "on")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# In production (Podman Compose), this is injected via the DJANGO_SECRET_KEY
# environment variable / .env file — see .env.example. The hardcoded value
# below is only used for local `manage.py runserver` development.
SECRET_KEY = os.environ.get(
    "DJANGO_SECRET_KEY",
    "django-insecure-!==u%c8dbr&n*xm(wyd9g^*ylxv9a6)uzxbk9k(qyjl@k9bwoo",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = _env_bool("DJANGO_DEBUG", default=True)

ALLOWED_HOSTS = [h.strip() for h in os.environ.get("DJANGO_ALLOWED_HOSTS", "").split(",") if h.strip()]
if DEBUG and not ALLOWED_HOSTS:
    ALLOWED_HOSTS = ["localhost", "127.0.0.1"]

CSRF_TRUSTED_ORIGINS = [
    o.strip() for o in os.environ.get("DJANGO_CSRF_TRUSTED_ORIGINS", "").split(",") if o.strip()
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # CodeLearn apps
    'accounts',
    'academics',
    'assignments',
    'quizzes',
    'attendance',
    'ml_engine',
    'code_runner',
    'campus',
    'messaging',
    'notifications',
]

AUTH_USER_MODEL = 'accounts.User'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'codelearn.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'campus.context_processors.unread_notification_count',
            ],
        },
    },
]

WSGI_APPLICATION = 'codelearn.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases
#
# Defaults to local sqlite (for `manage.py runserver` / `demo_pipeline`
# without any setup). When DB_ENGINE=mysql is set (as it is in
# podman-compose.yml, via .env), connects to the MySQL container instead —
# matching the original spec's "Database Container (MySQL)".

if os.environ.get("DB_ENGINE") == "mysql":
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': os.environ.get("DB_NAME", "codelearn"),
            'USER': os.environ.get("DB_USER", "codelearn"),
            'PASSWORD': os.environ.get("DB_PASSWORD", ""),
            'HOST': os.environ.get("DB_HOST", "db"),
            'PORT': os.environ.get("DB_PORT", "3306"),
            'OPTIONS': {'charset': 'utf8mb4'},
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

# All timestamps are stored in UTC internally (USE_TZ=True) — this only
# controls the timezone dates/times are *displayed* in. Configurable via
# .env for different deployments; defaults to Kathmandu since that's
# this project's context. A true per-user timezone preference (like
# theme_preference) would be a natural follow-up if users span multiple
# timezones.
TIME_ZONE = os.environ.get('DJANGO_TIME_ZONE', 'Asia/Kathmandu')

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'  # collectstatic target, served by nginx in production

# Content-hashed filenames (e.g. codelearn.a1b2c3d4.css) so a browser can
# NEVER serve a stale cached copy after a CSS/JS change — the URL itself
# changes whenever the file's content changes. This is what actually
# fixes "I updated the CSS but the old version still shows" for good,
# instead of relying on hard-refreshes or manually busting cache/volumes.
#
# ManifestStaticFilesStorage requires `collectstatic` to have been run
# at least once (it reads staticfiles.json to resolve {% static %} —
# with no manifest at all, it raises rather than falling back), which
# is fine in production (the Docker entrypoint always runs
# collectstatic before starting gunicorn) but would break local
# `manage.py runserver` / `manage.py test` on a fresh checkout where
# nobody has run collectstatic yet. So: strict hashed storage only when
# DEBUG is off; plain storage (no collectstatic required) in dev/tests.
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": (
            "django.contrib.staticfiles.storage.StaticFilesStorage"
            if DEBUG else
            "django.contrib.staticfiles.storage.ManifestStaticFilesStorage"
        ),
    },
}

# Media files (user uploads — profile pictures, etc.)
# Served by nginx in production (see nginx/nginx.conf's /media/ location);
# served by Django itself during local `manage.py runserver` (see urls.py).
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'dashboard'
LOGOUT_REDIRECT_URL = 'login'


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}
