# Generated by Django 6.1 on 2026-09-06 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_notifications',
            field=models.BooleanField(default=True, help_text='Whether this user wants email notifications for new messages, assignments, etc. (UI preference only — no email backend is configured in this project yet.)'),
        ),
        migrations.AddField(
            model_name='user',
            name='theme_preference',
            field=models.CharField(choices=[('LIGHT', 'Light'), ('DARK', 'Dark'), ('SYSTEM', 'Match system')], default='SYSTEM', max_length=10),
        ),
    ]
