# Generated by Django 6.1 on 2026-09-13 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='due_date',
            field=models.DateTimeField(blank=True, help_text='Optional — shown on the calendar view alongside assignment deadlines.', null=True),
        ),
    ]
