# Generated by Django 6.1 on 2026-09-11 01:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('GRADE', 'Grade posted'), ('WEAK_TOPIC', 'Weak topic flagged'), ('MESSAGE', 'New message'), ('SYSTEM', 'System')], default='SYSTEM', max_length=12)),
                ('message', models.CharField(max_length=255)),
                ('link', models.CharField(blank=True, help_text='Relative URL to navigate to', max_length=255)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
